<a href="https://colab.research.google.com/github/saiprasanthreddy/house-price-prediction-model/blob/main/house_price_prediction_feature_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

feature selection

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

pd.pandas.set_option('display.max_columns', None)

In [15]:
dataset=pd.read_csv('x_train.csv')

In [17]:
dataset.head()

,Id,SalePrice,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,12.247694,0.235294,0.728307,0.498996,0.666667,0.500,0.036765,0.098361,0.12250,0.125089,0.0,0.064212,0.140098,0.356155,0.413559,0.0,0.577712,0.333333,0.0,0.666667,0.5,0.375,0.333333,0.500000,0.000000,0.046729,0.50,0.386460,0.000000,0.111517,0.000000,0.0,0.0,0.0,0.0,0.090909,0.50,0.0,0.0,0.0
1,2,12.109011,0.000000,0.782545,0.525273,0.555556,0.875,0.227941,0.524590,0.00000,0.173281,0.0,0.121575,0.206547,0.503056,0.000000,0.0,0.470245,0.000000,0.5,0.666667,0.0,0.375,0.333333,0.333333,0.333333,0.289720,0.50,0.324401,0.347725,0.000000,0.000000,0.0,0.0,0.0,0.0,0.363636,0.25,0.0,0.0,0.0
2,3,12.317167,0.235294,0.740906,0.556925,0.666667,0.500,0.051471,0.114754,0.10125,0.086109,0.0,0.185788,0.150573,0.383441,0.419370,0.0,0.593095,0.333333,0.0,0.666667,0.5,0.375,0.333333,0.333333,0.333333,0.065421,0.50,0.428773,0.000000,0.076782,0.000000,0.0,0.0,0.0,0.0,0.727273,0.50,0.0,0.0,0.0
3,4,11.849398,0.294118,0.704684,0.524212,0.666667,0.500,0.669118,0.606557,0.00000,0.038271,0.0,0.231164,0.123732,0.399941,0.366102,0.0,0.579157,0.333333,0.0,0.333333,0.0,0.375,0.333333,0.416667,0.333333,0.074766,0.75,0.452750,0.000000,0.063985,0.492754,0.0,0.0,0.0,0.0,0.090909,0.00,0.0,0.0,0.0
4,5,12.429216,0.235294,0.794031,0.602280,0.777778,0.500,0.058824,0.147541,0.21875,0.116052,0.0,0.209760,0.187398,0.466237,0.509927,0.0,0.666523,0.333333,0.0,0.666667,0.5,0.500,0.333333,0.583333,0.333333,0.074766,0.75,0.589563,0.224037,0.153565,0.000000,0.0,0.0,0.0,0.0,1.000000,0.50,0.0,0.0,0.0

In [18]:
print(len(dataset.columns))

41

In [19]:
y_train=dataset[['SalePrice']]

In [20]:
x_train = dataset.drop(['Id','SalePrice'],axis=1)

In [21]:
feature_sel_model = SelectFromModel(Lasso(alpha=0.005, random_state=0))
feature_sel_model.fit(x_train, y_train)

SelectFromModel(estimator=Lasso(alpha=0.005, random_state=0))

In [22]:
feature_sel_model.get_support()

array([ True, False,  True,  True, False,  True,  True, False, False,
       False, False, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [23]:
selected_features = x_train.columns[(feature_sel_model.get_support())]

print('total features: {}'.format((x_train.shape[1])))
print('selected features: {}'.format(len(selected_features)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(feature_sel_model.estimator_.coef_ == 0)))

total features: 39
selected features: 10
features with coefficients shrank to zero: 29

In [24]:
selected_features

Index(['MSSubClass', 'LotArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
       '1stFlrSF', 'GrLivArea', 'BsmtFullBath', 'Fireplaces', 'GarageCars'],
      dtype='object')

In [26]:
x_train = x_train[selected_features].head()

In [27]:
x_train

,MSSubClass,LotArea,OverallQual,YearBuilt,YearRemodAdd,1stFlrSF,GrLivArea,BsmtFullBath,Fireplaces,GarageCars
0,0.235294,0.498996,0.666667,0.036765,0.098361,0.356155,0.577712,0.333333,0.000000,0.50
1,0.000000,0.525273,0.555556,0.227941,0.524590,0.503056,0.470245,0.000000,0.333333,0.50
2,0.235294,0.556925,0.666667,0.051471,0.114754,0.383441,0.593095,0.333333,0.333333,0.50
3,0.294118,0.524212,0.666667,0.669118,0.606557,0.399941,0.579157,0.333333,0.333333,0.75
4,0.235294,0.602280,0.777778,0.058824,0.147541,0.466237,0.666523,0.333333,0.333333,0.75